#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# Rodar o phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Erro no PHPSTAN";
    exit 1;
fi;

# rodar os testes
php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "Erro nos testes";
    exit 1;
fi;

exit 0;
